[2023-01-27T00:00:05.970+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2023-01-26T12:00:00+00:00 [queued]>
[2023-01-27T00:00:05.977+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2023-01-26T12:00:00+00:00 [queued]>
[2023-01-27T00:00:05.977+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T00:00:05.977+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-27T00:00:05.977+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T00:00:05.987+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2023-01-26 12:00:00+00:00
[2023-01-27T00:00:05.992+0000] {standard_task_runner.py:55} INFO - Started process 788 to run task
[2023-01-27T00:00:05.994+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'scheduled__2023-01-26T12:00:00+00:00', '--job-id', '336', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpcdab2fni']
[2023-01-27T00:00:05.995+0000] {standard_task_runner.py:83} INFO - Job 336: Subtask store_user
[2023-01-27T00:00:06.036+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.store_user scheduled__2023-01-26T12:00:00+00:00 [running]> on host a353ca64b4e2
[2023-01-27T00:00:06.081+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-01-26T12:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-26T12:00:00+00:00
[2023-01-27T00:00:06.082+0000] {postgres.py:129} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2023-01-27T00:00:06.088+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-01-27T00:00:06.093+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-27T00:00:06.098+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, execution_date=20230126T120000, start_date=20230127T000005, end_date=20230127T000006
[2023-01-27T00:00:06.126+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-27T00:00:06.143+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
