[2023-01-28T13:20:16.382+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: parallel_dag.transform scheduled__2023-01-27T00:00:00+00:00 [queued]>
[2023-01-28T13:20:16.450+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: parallel_dag.transform scheduled__2023-01-27T00:00:00+00:00 [queued]>
[2023-01-28T13:20:16.451+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-28T13:20:16.451+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-28T13:20:16.451+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-28T13:20:16.517+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): transform> on 2023-01-27 00:00:00+00:00
[2023-01-28T13:20:16.593+0000] {standard_task_runner.py:55} INFO - Started process 1447 to run task
[2023-01-28T13:20:16.613+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'parallel_dag', 'transform', 'scheduled__2023-01-27T00:00:00+00:00', '--job-id', '377', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp5nqcq8po']
[2023-01-28T13:20:16.615+0000] {standard_task_runner.py:83} INFO - Job 377: Subtask transform
[2023-01-28T13:20:16.946+0000] {task_command.py:376} INFO - Running <TaskInstance: parallel_dag.transform scheduled__2023-01-27T00:00:00+00:00 [running]> on host d99e4e2caeb1
[2023-01-28T13:20:17.453+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2023-01-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-27T00:00:00+00:00
[2023-01-28T13:20:17.456+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-28T13:20:17.457+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sleep 20']
[2023-01-28T13:20:17.516+0000] {subprocess.py:86} INFO - Output:
[2023-01-28T13:20:27.023+0000] {local_task_job.py:228} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-01-28T13:20:27.027+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 1447. PIDs of all processes in the group: [1451, 1447]
[2023-01-28T13:20:27.027+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 1447
[2023-01-28T13:20:27.028+0000] {taskinstance.py:1562} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-28T13:20:27.029+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-01-28T13:20:27.164+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1451, status='terminated', started='13:20:16') (1451) terminated with exit code None
[2023-01-28T13:20:27.165+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1447, status='terminated', exitcode=0, started='13:20:15') (1447) terminated with exit code 0
